### ISSUE TITLE
'tuple' object has no attribute 'labels'

### ISSUE THREAD

**Issue by louisdj** [wosc/prometheus-uptimerobot#3]
`Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "build/bdist.linux-x86_64/egg/prometheus_client/exposition.py", line 45, in prometheus_app
    output = encoder(r)
  File "build/bdist.linux-x86_64/egg/prometheus_client/openmetrics/exposition.py", line 23, in generate_latest
    if s.labels:
AttributeError: ("'tuple' object has no attribute 'labels'", Metric(uptimerobot_status, Numeric status of the monitor, gauge, , [('uptimerobot_status', {'monitor_name': u'Confluence', 'monitor_type': 'http', 'monitor_url': u'********'}, 2), ...`

**Comment by derfel** [comment]
You can try my PR #4

**Comment by krzee** [comment]
i think this was fixed, @louisdj should this be closed now?

**Comment by mKIRArasif** [comment]
> i think this was fixed, @louisdj should this be closed now?

The problem is happening with QuickOSM plugin in QGIS on Fedora 37.

**Comment by wosc** [comment]
As far as I can tell this issue was fixed in version 1.2.0 (released 2021-10-22)
