### ISSUE TITLE
api_key

### ISSUE THREAD

**Issue by nicosistemas** [wosc/prometheus-uptimerobot#5]
Hello, my query is about where to add the API_KEY generated in the Uptimerobot portal, because I can't find the configuration.

where do i change this line?
[default]
api_key = 123456789

or just add a config file with the api_key parameter?

config file:

#
api_key=u863105-29bf65368cf
#

Sorry that the question is basic but I can not understand it.
Thanksssss!!

**Comment by wosc** [comment]
You create a configuration file, for example `myconfig.ini` with this content:

```
[default]
api_key = your-api-key-goes-here
```

Then you run the program like this `uptimerobot_exporter --config myconfig.ini`
